### ISSUE TITLE
Better Junimos is asking to be updated

### ISSUE THREAD

**Issue by PupOgre** [hawkfalcon/Stardew-Mods#11]
I have the latest version, but for some reason it wants a new version that doesn't exist. It also points to "Better JUKEBOX" instead of "Better Junimos" when I go to update from ModDrop. https://www.moddrop.com/stardew-valley/mods/984775-better-jukebox is the link embedded from smapi.io/mods under "Better Junimos".

**Comment by Pathoschild** [comment]
That's a mistake with the compatibility list. I just fixed it, though it might be cached for up to an hour.

**Comment by Pathoschild** [comment]
The change should be live at this point. Thanks for reporting it!

**Comment by hawkfalcon** [comment]
Thanks Pathos!
