### ISSUE TITLE
Stardew Valley .4 update.

### ISSUE THREAD

**Issue by Mizzion** [hawkfalcon/Stardew-Mods#2]
Stardew was recently updated to 1.4, but I noticed that your git is behind in versions compared to the released version. If you push your update to your git I can update it and send in PR to you. 

If you want to update it yourself, SDV changed the JunimoHarvester constructor. Here's an updated version that is commented with my fixes. 
[Util.zip](https://github.com/hawkfalcon/Stardew-Mods/files/3903840/Util.zip)

**Comment by hawkfalcon** [comment]
Thanks for noticing, I forgot to commit a very small bug fix. I'll update my mod at some point this week and will definitely include your changes! Thank you :D
