### ISSUE TITLE
CustomQuestExpiration - Quests don't give tickets

### ISSUE THREAD

**Issue by amburo** [hawkfalcon/Stardew-Mods#24]
With the new 1.6 update, sometimes quests will also give Prize Tickets when completed - with custom quest expiration installed the quests no longer show the tickets on the quest once accepted nor give them as a reward for completion.

**Comment by hawkfalcon** [comment]
I'm surprised someone still uses that mod, and I'm surprised it still works at all - it hasn't been updated in 5 years!
