### ISSUE TITLE
Junimos not planting anything/error when constructing hut

### ISSUE THREAD

**Issue by SpringsSong** [hawkfalcon/Stardew-Mods#26]
Hi,

I was testing this mod out prior to adding it to my family's multiplayer save, and came across a couple of things,

First: When warping to the Wizard to build the test hut, I received an error, shown here: https://smapi.io/log/d3613ca0778f40f4b75a677c1feac8ec

Second: With progression disabled, I put parsnip seeds in the Junimo hut, along with Deluxe Speed-Gro. After a _consdierable_ amount of time (I froze time at 6am to set up a spot, unfroze it after building, and the Junimos did not start applying fertilizer until 8am or 9am), the Junimos began to apply fertilizer... but not the seeds. When changing the day, this persisted.

**Comment by hawkfalcon** [comment]
Yeah, it's still buggy, which is why I haven't released the update. 

Thank you for narrowing down the bugs, let me know if you find any more! I'll work on them when I'm back from my trip in a couple of  weeks.

**Comment by SpringsSong** [comment]
If I come across any others, I'll definitely let you know! I plan on putting it through my usual paces once my custom OmniFarm map is updated for the new stuff in 1.6 because that made use of the expanded area.

**Comment by jacob-keller** [comment]
I have had issues as well with Junimos not planting any seeds, but being able to fertilize. I tried attaching a debugger but none of the planting ability methods seemed to trigger. It's late here, so I'll try again tomorrow.

**Comment by jacob-keller** [comment]
I think I figured out whats wrong here. The changes to support string-based item values instead of integers broke the category logic, so the Junimos can no longer locate required items in the huts. It looks like we need to handle this somehow in UpdateHutContainsItems

Specifically the change from itemId > 0 to itemId != "0" is definitely incorrect.

**Comment by hawkfalcon** [comment]
Nice find. Thank you!

**Comment by jacob-keller** [comment]
Yea this should be fixed in #29 at least on my save file.
