### ISSUE TITLE
Flower Harvest

### ISSUE THREAD

**Issue by Sackarin** [hawkfalcon/Stardew-Mods#33]
Junimos are still harvesting flowers despite having the option not to enabled. Option isn't listed in the Junimo progression page either. Other options seem to work fine. (Noted on ongoing save with progression having been disabled in config)

**Comment by hawkfalcon** [comment]
Strange, I wonder what changed? https://github.com/hawkfalcon/Stardew-Mods/blob/master/BetterJunimos/Abilities/Base/HarvestCropsAbility.cs#L62

**Comment by Sackarin** [comment]
Unfortunately I know nothing about coding, so I couldn't tell you. I will say that I have (a lot) of other mods, although I don't think any of those affect flowers, buildings or junimos. Could also be the aforementioned ongoing save that is messing with things. Just thought I would tell you in case other people encounter this problem. If it's a 'me' problem, I'll live with that :)

**Comment by coucou0610** [comment]
You're not the only one with this problem, so am I. Even if I set it up, Junimos will still be there to harvest the flowers.

**Comment by Geethebluesky** [comment]
Same issue here, and I tried Ignoring the tiles with flowers--the junimos still harvest from ignored tiles as well.

**Comment by ext** [comment]
I did some debugging with this one and unless I'm mistaken `item.Category` is set to `-9` instead of `-80` which makes the `item.Category == StardewValley.Object.flowersCategory` condition fail.

**Comment by hawkfalcon** [comment]
Thans @ext! 591 is tulip, so you'd think it would be flowersCategory...

**Comment by hawkfalcon** [comment]
Apparently there's a second constructor for Object which always sets it to BigCraftable. I think I fixed it - https://github.com/hawkfalcon/Stardew-Mods/releases/tag/3.0.1-beta

**Comment by goingcrazy1st** [comment]
Finally spring on my save, planted flowers and the junimos did not harvest them, just the way I told them in the config. Using 3.0.1 beta. Thank you, Thank you.
