### ISSUE TITLE
Better Junimos Cant go into greenhouse [log]

### ISSUE THREAD

**Issue by TwoPointInfinity** [hawkfalcon/Stardew-Mods#35]
![image](https://github.com/hawkfalcon/Stardew-Mods/assets/7976722/d2815137-81fb-4292-b8ba-50a3561a26d3)
https://smapi.io/log/060c2d2dbc8c4f09b649c9e9f5136b3e
The error is under the [game] selection option in the smapi log. the junimos will stand outside the greenhouse unable to go inside. the log will spam, the game will lag, and the junimos will be unable to do anything until the option is disabled. I haave progressive mode enabled and the junimos have been given the items to work. See images provided.
![image](https://github.com/hawkfalcon/Stardew-Mods/assets/7976722/4210fafc-338c-4f17-89af-20983b9ad10a)
![image](https://github.com/hawkfalcon/Stardew-Mods/assets/7976722/cd20ac1e-832e-4980-bb6d-1d7dd1ce5c8a)
![image](https://github.com/hawkfalcon/Stardew-Mods/assets/7976722/e169a89a-7d76-4a59-91af-ba0c5dd2d4bb)
![image](https://github.com/hawkfalcon/Stardew-Mods/assets/7976722/dc46dffd-e7e3-405b-88bd-7750065d1129)
![image](https://github.com/hawkfalcon/Stardew-Mods/assets/7976722/ac02483e-ed90-4355-9c22-97bd10d1f094)
![image](https://github.com/hawkfalcon/Stardew-Mods/assets/7976722/8340d3a2-16c4-4248-9815-514adfc79fbe)

**Comment by TwoPointInfinity** [comment]
I hope im not doing anything wrong here, i didnt change many settings. If you need more information please reach out to me here.

**Comment by goingcrazy1st** [comment]
I had a couple of Junimos in the greenhouse, but they weren't doing anything. Here's my log:  https://smapi.io/log/dd25f99aa96a451091def51070ca2089
Thank you for being willing to come back to do this. Know that everyone's efforts to get this working is greatly appreciated.

**Comment by Caymort** [comment]
I have the same problem as goingcrazy1st. The Junimos enter the greenhouse and stuck one place.

**Comment by junioriz** [comment]
Same for me, the junimos get stuck in the greehouse. I have Aimon's fancy greenhouse downloaded so maybe it's that ?

**Comment by Bryzillah** [comment]
I'm also having goingcrazy1st's problem they just get stuck on one tile in the greenhouse.

**Comment by hawkfalcon** [comment]
I repro'd this, but can't figure out why....

**Comment by zitkin** [comment]
I poked around and only seemed to find this (sorry if overstepping)...
When junimos are spawned in the greenhouse via `Util.SpawnJunimoAtPosition`, when it calls the `JunimoHarvester` constructor, setting the location to the Greenhouse `GameLocation` causes the `HomeId` property to be a bunch of 0s, and the `home` property to be null as well. Something with the Greenhouse `GameLocation` is messing up the process of getting the `netHome` NetGuid value... maybe because the home property `get` and `set` methods use `base.currentLocation.buildings.GuidOf()`? 
If I set the location to Farm first when calling the constructor, everything populates just fine, until I change the location back to Greenhouse, then those properties get messed up again.

**Comment by hawkfalcon** [comment]
@zitkin  you are definitely not overstepping you are awesome. Thank you - gives me a better place to start. I haven't touched SDV modding for like 4 years

**Comment by Miguel-Thewolf** [comment]
> I poked around and only seemed to find this (sorry if overstepping)... When junimos are spawned in the greenhouse via `Util.SpawnJunimoAtPosition`, when it calls the `JunimoHarvester` constructor, setting the location to the Greenhouse `GameLocation` causes the `HomeId` property to be a bunch of 0s, and the `home` property to be null as well. Something with the Greenhouse `GameLocation` is messing up the process of getting the `netHome` NetGuid value... maybe because the home property `get` and `set` methods use `base.currentLocation.buildings.GuidOf()`? If I set the location to Farm first when calling the constructor, everything populates just fine, until I change the location back to Greenhouse, then those properties get messed up again. Anyway, if `home` is null, this messes up the pathfinding.

Vanilla code for home property

[XmlIgnore]
    public JunimoHut home
    {
        get
        {
            if (!base.currentLocation.buildings.TryGetValue(netHome.Value, out var value))
            {
                return null;
            }

            return value as JunimoHut;
        }
        set
        {
            netHome.Value = base.currentLocation.buildings.GuidOf(value);
        }
    }
    
I will replace with harmony

replacements.Add("get_home", junimoType, typeof(PatchGet_home));
            replacements.Add("set_home", junimoType, typeof(PatchSet_home));

[HarmonyPriority(Priority.Low)]
  public class PatchGet_home {
      public static void Postfix(ref JunimoHut __result, ref NetGuid ___netHome)
      {
          __result = Util.GetHutFromId(___netHome.Value);
      }
  }

  [HarmonyPriority(Priority.Low)]
  public class PatchSet_home {
      public static void Postfix(JunimoHut value, ref NetGuid ___netHome)
      {
          ___netHome.Value = Util.GetHutIdFromHut(value);
      }
  }

This will fix many others Guid 00000-0000 errors

Fix is working on https://github.com/Miguel-Thewolf/Stardew-Mods/tree/modded_greenhouse
I need test with tiny greenhouse mod, and greenhouses in other locations, when i finished the tests i create pull request
