### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by krisa-b** [hawkfalcon/Stardew-Mods#37]
Hi, I don't really see any issues in game, but smapi is throwing a bit of a fit: https://smapi.io/log/da503642ef364f20a880ffa7ff206d2d. I have one hut at the regular farm and I've placed one on the island farm, but not used the junimos there yet. They are harvesting flowers though, but that's not in the log, I think

**Comment by hawkfalcon** [comment]
This seems to be a conflict with another mod, maybe a custom item in the hut?

**Comment by krisa-b** [comment]
Hmm, does it react to retextures like that? That’s the only thing custom I can think of that has been inside the hut (Vanilla tweaks). No fully custom seeds, crops or flowers. Outside the hut I have ‘the return of immersive sprinklers’, if that might confuse them?

**Comment by krisa-b** [comment]
Yes, I thought I mentioned that but I see now that I could have been clearer:)

**Comment by hawkfalcon** [comment]
My bad - I missed that. The mod is currently hardcoded to the farm. Someone just made a PR to potentially fix that, though. Maybe that will work

**Comment by krisa-b** [comment]
Ah that makes sense! I’ll just remove it I think, since I’m not really using it. Thanks for your time and a great mod!

**Comment by hawkfalcon** [comment]
Closing as same as #34
