### ISSUE TITLE
junimos dont work on ginger island farm

### ISSUE THREAD

**Issue by irismews** [hawkfalcon/Stardew-Mods#39]
I'm using the "buildable ginger island farm" mod but with better junimos enabled they dont work on the farm at all. smapi log is here: https://smapi.io/log/e1bf026eb91c4438a5a2d7a00b596d35 let me know if you need anything else

**Comment by hawkfalcon** [comment]
Yeah, that's a mod conflict. This mod only works on the farm :/

**Comment by hawkfalcon** [comment]
Same as #34
