### ISSUE TITLE
Junimos wont harvest town farm while on island

### ISSUE THREAD

**Issue by irismews** [hawkfalcon/Stardew-Mods#41]
I was at the island for around a week, and during that time i had a bunch of fiber seeds the junimos should have harvested. got back to the regular farm at around 7pm, and realized they had only just started harvesting then. smapi log here: https://smapi.io/log/cfc93ee1377e49959e7776157fe45382

**Comment by hawkfalcon** [comment]
Do you have a hut on your island?

**Comment by hawkfalcon** [comment]
I'm not sure if they even do work in vanilla

**Comment by irismews** [comment]
Just checked without a hut on the island and that did fix it. Just saw you posted a new beta, I can check again with that and report back

**Comment by irismews** [comment]
With the new beta + hut on island they still dont work, but do work when no huts are on the island 👍
