### ISSUE TITLE
Junimos Won't Replant Seeds

### ISSUE THREAD

**Issue by BlossomXoXoX** [hawkfalcon/Stardew-Mods#43]
No matter what settings i enable, My junimos won't replant seeds...

**Comment by Geethebluesky** [comment]
Same here, no planting ever happens. They can fertilize (not always but most of the time), but don't ever plant seeds.

**Comment by hawkfalcon** [comment]
I can't repro this, are your seeds in season? Are they in the hut?

**Comment by hawkfalcon** [comment]
You're running Better Junimos 3.0.0-unofficial.1-p1xel8ted lmao update the mod

**Comment by Geethebluesky** [comment]
They are still not planting with the 3.0.1 beta.
- Yes, the seeds are in season, everything in the hut is unlocked, I have no wages to pay (disabled that) and PlantCrops is true.

**Comment by D3vilEye** [comment]
> You're running Better Junimos 3.0.0-unofficial.1-p1xel8ted lmao update the mod

Ohh i'm so sorry... I've updated to the lastest version and now planting seems to work! TYVM!!!

**Comment by Geethebluesky** [comment]
@D3vilEye How long does it take for the junimos to start planting seeds when you put them in a hut?

I left seeds in a hut for 4 game hours and nothing happened.

**Comment by D3vilEye** [comment]
> @D3vilEye How long does it take for the junimos to start planting seeds when you put them in a hut?
> 
> I left seeds in a hut for 4 game hours and nothing happened.

I've had to remove then rebuild my Junino Hunt, then they insta started plating.

**Comment by Geethebluesky** [comment]
Thanks I'll try that!

**Comment by Geethebluesky** [comment]
It's not working for me. I destroyed my 3 huts, rebuilt them from the wizard's tower, and it's Spring 1, there's 400 spring seeds in the hut and none of them are getting planted. :/
