### ISSUE TITLE
Better Junimos not taking speedgro fertilizer into account when planting seeds.

### ISSUE THREAD

**Issue by Valamyr** [hawkfalcon/Stardew-Mods#46]
I've noticed a bug with the junimos seeding fertilized soil.

After (manually) placing deluxe speed-gro on a field and letting Better junimos plant pumpkins on it (by placing seeds in their hut), the fertilizer was not accounted for. I am agriculurist; the 13 day duration is cut to 11 without fertilizer and down to 8 with fertilizer. Everything the junimos planted will take 11 days to grow according to tooltips provided by another mod.

When I noticed this, I took some seeds and started helping them plant. Everything I planted personally shows a 8 days growth period (taking the fertilizer into account). So I must conclude there is an issue here, unfortunately. Junimo-planting should take fertilizer into account as well. I have not tested anything about quality-fertilizers but it might suffer from the same issue.

Thank you for the mod and any effort to fix the little issues left, really appreciated! 

(Copy/paste of my message on Nexus, I noticed the author has requested bugs to be reported here)

**Comment by hawkfalcon** [comment]
Seems like junimos are only taking into account fertilizer they put down. Duping to #44

**Comment by aaKugelblitz** [comment]
I know this issue is closed but i am definitely still experiencing this issue. I've tried letting the junimos place all the fertalizier but it seems theres still tiles that the junimos ignore fertilizer for
