### ISSUE TITLE
Game lags and freezes/locks up

### ISSUE THREAD

**Issue by BxckyKujo** [hawkfalcon/Stardew-Mods#48]
I barely have any junimos on my farm, but my game seems to freeze up alot (usually lasts around 10 seconds). I haven't had this issue until downloading this mod... also, some junimos seem to just stand around and not plant anything.. whereas others in a different area plant. I'm so confused lol. Please help

**Comment by hawkfalcon** [comment]
I need more information. What other mods do you have?
