### ISSUE TITLE
Junimo harvesting not counting towards help wanted quest

### ISSUE THREAD

**Issue by goingcrazy1st** [hawkfalcon/Stardew-Mods#49]
I have a quest to harvest & ship 100 artichokes. Grew them and had the Junimos harvest but the items didn't count towards the items harvested portion of the quest. 
Here's my log:  https://smapi.io/log/796064d5b77d4a6092352696eb1f7641

**Comment by hawkfalcon** [comment]
Yeah, this is true (you didn't harvest them.)
