### ISSUE TITLE
Incompatible with RSV?

### ISSUE THREAD

**Issue by Hunney143** [hawkfalcon/Stardew-Mods#51]
Despite being able to build Junimo huts on RSV, they never appear, the menu is inaccessible and nothing happens when the fields are planted around them.

I'm also getting several errors popping up in my SMAPI console. Is this just an issue with RSV?

Here is my SMAPI log in case you want to take a look.
https://smapi.io/log/699aaa0d0011482d8f8109cc4f3cd913

**Comment by hawkfalcon** [comment]
Going to assume 'RSV' contains extra huts not on the farm. Same as #34
