### ISSUE TITLE
Junimos not harvesting crops in field with Giant crop

### ISSUE THREAD

**Issue by goingcrazy1st** [hawkfalcon/Stardew-Mods#53]
I have the GMCM set for the junimos to not harvest giant crops. When I harvest the giant crop, they water but don't harvest any of the non-giant crops. I hope that makes sense. The SMAPI log is not showing any errors, but here it is just in case. https://smapi.io/log/76f43890b4474194924a88d724e04fdd
I am going to set the config to harvest giant crops and see if that changes anything. I can also see what happens if I leave the setting and don't harvest the giant crop, but I think they are usually well into harvesting by the time I get out of the farmhouse and that's not been happening.

Edit: Ok, I tried not harvesting the giant crop myself with the config set for the junimos not to harvest it either. They just didn't harvest anything in that field. Then I restarted the day with the config set for them to harvest the giant crop and they harvested everything in the field, except the giant crop. Here's the log for the harvest giant crop setting.  https://smapi.io/log/0745896d6b454787976019c6068c2d02  
SMAPI still says no errors. Also, forgot to say that the junimos from other huts are harvesting their assigned fields with no issues.

**Comment by hawkfalcon** [comment]
So I think this is intentional. The toggle is to prevent harvesting anything that could become a giant crop

**Comment by goingcrazy1st** [comment]
Thank you for your response. I had that thought after I posted this, but in 1.5 the junimos would harvest anything that wasn't already a giant crop on the day the harvest was ready. I am really good with it working the way it was intended.
