### ISSUE TITLE
Not planting modded seeds

### ISSUE THREAD

**Issue by Geethebluesky** [hawkfalcon/Stardew-Mods#54]
I finally have my Junimos planting, but they only seem to recognize vanilla seeds.

It's currently Spring 1, and the junimos are busily planting all the base-game spring seeds normally after paying 5 iron bars, but they're ignoring the agave.

I'm sure of this because I have 3 huts, the leftmost only has 400 [Cornucopia - More Crops](https://www.nexusmods.com/stardewvalley/mods/19508) agave seeds in there, the middle has a mix of vanilla and modded seeds and the last one has mixed flowers (vanilla and [modded](https://www.nexusmods.com/stardewvalley/mods/20290)). 

Only the vanilla seeds are getting planted in 2 and 3, nothing's happening with the leftmost hut except fertilizing, watering, etc.

This is with beta 3.0.1.

**Comment by hawkfalcon** [comment]
Ah, yeah. It doesn't support custom seeds. Probably fixable if you want to submit a PR.

**Comment by Geethebluesky** [comment]
I can't help with that unfortunately but I'm willing to test.

**Comment by Miguel-Thewolf** [comment]
> I can't help with that unfortunately but I'm willing to test.


https://github.com/Miguel-Thewolf/Stardew-Mods/tree/modded_crop_fix

The fix is compatible with any other custom mod; if the item is a crop, then it can be planted.
I will create the pull request once the other one has been accepted. I forgot create a separate branch for the first.
