### ISSUE TITLE
Random Junimos

### ISSUE THREAD

**Issue by goingcrazy1st** [hawkfalcon/Stardew-Mods#64]
I hope this is where I should report this. I compiled the new merges (hope I did it right, still learning) and everything works except I now have random Junimos spawning in different places. This doesn't really break anything, it's just odd. I removed all extra mods except content patcher and GMCM. No errors in SMAPI. The Junimos don't always spawn in the same place on different save days, but they most consistently appear in Cindersnap Forest and next to the community center. I did try this, separately, with both Buildable Ginger Island and Build Anything, Anywhere and it works with both of those mods. On this save day, for this log, I can very happily report that the Junimos also work on Ginger Island without either one of those mods installed. So yay!! I placed the huts on Ginger Island using Buildable Ginger Island and then removed the mods for this log, so I can't say if you need those mods to build them on Ginger Island. 
Here is the log. Hope it shows something. 
https://smapi.io/log/c2befa28ad73472c99069d9de8fe2d8b
Thank you to everyone who worked on this to get it working to this extent. Awesome!!!

**Comment by hawkfalcon** [comment]
Haha, I kinda love it

**Comment by goingcrazy1st** [comment]
Yeah, it was kind of cool to see them living their best life splashing around in the water. The one in the middle of a cliff and the one in the middle of the dining room wall were just a little out of place. Thought maybe I could put a picture frame around the one in the dining room...animated art LOL. Thank you for giving up your precious time to get this working. And to the other modders for helping to fix it. No more random Junimos and the greenhouse is working perfectly. Thank you, thank you.
