### ISSUE TITLE
Money Drain when junimos work in the Rain

### ISSUE THREAD

**Issue by Leekyboatstudios** [hawkfalcon/Stardew-Mods#66]
When junimos work in the rain (storms specifically) as soon as they leave their huts my money starts draining quickly. Like I am making purchases but nothing is being purchased. Only way I was able to avoid this is to not have the junimos work in the rain at all.

**Comment by hawkfalcon** [comment]
I can't reproduce this. I don't think the mod ever uses money?

**Comment by Leekyboatstudios** [comment]
Yeah I found it weird too. It only happens on stormy days when the Junimos leave their huts. I made it where the junimos can not work during the rain at all and it has not happened again. I don't know why it happens or how to recreate it either. I found a work around, so it is all good.

**Comment by hawkfalcon** [comment]
So weird. I made it rain and nothing happened. If it happens again feel free to reopen this!

**Comment by Leekyboatstudios** [comment]
I noticed it only happened during **stormy** weather, but I have tons of mods so it could be it reacting weird with another mod. I removed mods and checked over and over and the only way to fix it was to turn off work during rain.  If it pops up again I will definitely let you know, but I don't intend to let them work during the rain so it likely will not.
